-- +goose Up
-- +goose StatementBegin
CREATE TABLE cart_items(
    id      BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id  BIGINT  NOT NULL,
    user_id UUID    NOT NULL,
    count   INT     NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE cart_items;
-- +goose StatementEnd